Treaty of New York and Western Collapse
The-Grand-Combination/The-Grand-Combo pull request #203
Opened 2023-01-04 18:36 UTC by Perfo-6

2023-01-08 13:50 UTC, ColdSlav reviewed
Looks good so far, please let me know of any other changes you haven't commited yet.

2023-01-08 16:25 UTC, ColdSlav requested changes
Everything good, apart from one file with encoding error

2023-01-08 16:25 UTC, ColdSlav commented on TGC/localisation/00_events_10000000.csv
> +EVTDESC4395438;This event ensures that Pet�n is getting colonized.;;;;;;;;;;;x
Encoding error, please fix

2023-01-10 20:31 UTC, GeneralVonGelre reviewed
All a-ok..

2023-01-10 20:31 UTC, GeneralVonGelre commented on TGC/localisation/00_events_10000000.csv
> +EVTDESC4395438;This event ensures that Pet�n is getting colonized.;;;;;;;;;;;x
Its not.

2023-01-11 23:53 UTC, ColdSlav commented
@GeneralVonGelre Are we good for merging this one?

2023-01-14 17:33 UTC, ColdSlav approved these changes
:+1:

2023-01-14 17:50 UTC, merged